package report

import (
	"fmt"
	"html"
	"sort"
	"strings"
	"time"

	"github.com/ghe-wizard/ghe-wizard/internal/engine"
	"github.com/ghe-wizard/ghe-wizard/internal/rules"
	"github.com/ghe-wizard/ghe-wizard/internal/scoring"
)

// HTML renders a self-contained, styled HTML scorecard suitable for sharing or
// archiving (no external assets or scripts).
func HTML(sc *engine.Scorecard) string {
	var b strings.Builder
	gr := grade(sc.Summary.Score)

	b.WriteString(`<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">`)
	b.WriteString(`<meta name="viewport" content="width=device-width,initial-scale=1">`)
	fmt.Fprintf(&b, `<title>GHE Scorecard · %s</title>`, html.EscapeString(sc.Enterprise))
	b.WriteString(`<style>` + htmlCSS + `</style></head><body>`)

	// Header
	fmt.Fprintf(&b, `<header><div class="brand">🛡️ GHE Best-Practices Scorecard</div>
		<div class="meta">%s · %s</div></header>`,
		html.EscapeString(sc.Enterprise), sc.GeneratedAt.Format(time.RFC1123))

	// Score + summary
	fmt.Fprintf(&b, `<section class="top"><div class="score" style="--c:%s">
		<div class="num">%d</div><div class="den">/ 100</div><div class="grade">Grade %s</div></div>`,
		gr.color, sc.Summary.Score, gr.letter)
	b.WriteString(`<div class="counts">`)
	for _, s := range []rules.Status{rules.StatusFail, rules.StatusWarn, rules.StatusManual, rules.StatusError, rules.StatusPass} {
		fmt.Fprintf(&b, `<div class="count %s"><span class="n">%d</span><span class="k">%s</span></div>`,
			s, sc.Summary.Counts[string(s)], s)
	}
	b.WriteString(`</div></section>`)

	// Results grouped by domain
	byDomain := map[rules.Domain][]rules.Result{}
	var domains []rules.Domain
	for _, r := range sc.Results {
		if _, ok := byDomain[r.Meta.Domain]; !ok {
			domains = append(domains, r.Meta.Domain)
		}
		byDomain[r.Meta.Domain] = append(byDomain[r.Meta.Domain], r)
	}
	sort.Slice(domains, func(i, j int) bool { return domains[i] < domains[j] })

	for _, d := range domains {
		fmt.Fprintf(&b, `<h2>%s</h2><table><thead><tr><th>Rule</th><th>Status</th><th>Severity</th><th>Finding</th></tr></thead><tbody>`, title(string(d)))
		for _, r := range byDomain[d] {
			rem := ""
			if r.Remediation != "" {
				rem = `<div class="fix"><b>Fix:</b> ` + html.EscapeString(r.Remediation) + `</div>`
			}
			fmt.Fprintf(&b, `<tr>
				<td class="rid"><a href="%s" target="_blank" rel="noopener">%s</a><div class="rt">%s</div></td>
				<td><span class="chip %s">%s</span></td>
				<td><span class="sev %s">%s</span></td>
				<td>%s%s</td></tr>`,
				html.EscapeString(r.Meta.DocsURL), html.EscapeString(r.Meta.ID), html.EscapeString(r.Meta.Title),
				r.Status, r.Status, r.Meta.Severity, r.Meta.Severity,
				html.EscapeString(r.Detail), rem)
		}
		b.WriteString(`</tbody></table>`)
	}

	b.WriteString(`<footer>Generated by ghe-wizard · assessment is read-only</footer>`)
	b.WriteString(`</body></html>`)
	return b.String()
}

type gradeInfo struct {
	letter string
	color  string
}

func grade(score int) gradeInfo {
	return gradeInfo{letter: scoring.Letter(score), color: scoring.Color(score)}
}

func title(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

const htmlCSS = `
:root{--bg:#0d1117;--panel:#161b22;--border:#30363d;--fg:#e6edf3;--muted:#9aa7b4}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--fg);font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;font-size:14px}
header{padding:22px 28px;border-bottom:1px solid var(--border)}
.brand{font-size:18px;font-weight:700}.meta{color:var(--muted);font-size:13px;margin-top:4px}
.top{display:flex;gap:28px;align-items:center;padding:24px 28px;flex-wrap:wrap}
.score{display:flex;align-items:baseline;gap:8px;padding:16px 22px;border:1px solid var(--border);border-radius:12px;background:var(--panel)}
.score .num{font-size:44px;font-weight:800;color:var(--c)}
.score .den{color:var(--muted)}.score .grade{margin-left:10px;color:var(--c);font-weight:700}
.counts{display:flex;gap:12px;flex-wrap:wrap}
.count{display:flex;flex-direction:column;padding:12px 16px;border:1px solid var(--border);border-radius:10px;background:var(--panel);min-width:90px}
.count .n{font-size:22px;font-weight:700}.count .k{color:var(--muted);font-size:12px;text-transform:capitalize}
.count.fail .n{color:#f85149}.count.warn .n{color:#d29922}.count.manual .n{color:#58a6ff}.count.error .n{color:#db6d28}.count.pass .n{color:#2ea043}
h2{padding:0 28px;margin:26px 0 8px;font-size:16px;text-transform:capitalize;border-left:3px solid #2ea043;margin-left:28px;padding-left:10px}
table{width:calc(100% - 56px);margin:0 28px 8px;border-collapse:collapse}
th,td{text-align:left;padding:10px 12px;border-bottom:1px solid var(--border);vertical-align:top;font-size:13px}
th{color:var(--muted);font-weight:600}
.rid a{color:#58a6ff;text-decoration:none;font-family:ui-monospace,Consolas,monospace}
.rt{color:var(--fg);margin-top:3px;font-weight:500}
.chip{padding:3px 10px;border-radius:20px;font-size:12px;font-weight:600;text-transform:capitalize}
.chip.pass{background:rgba(46,160,67,.15);color:#2ea043}.chip.fail{background:rgba(248,81,73,.15);color:#f85149}
.chip.warn{background:rgba(210,153,34,.15);color:#d29922}.chip.manual{background:rgba(88,166,255,.15);color:#58a6ff}
.chip.error{background:rgba(219,109,40,.15);color:#db6d28}
.sev{font-size:11px;text-transform:uppercase;color:var(--muted)}
.sev.critical{color:#f85149}.sev.high{color:#db6d28}.sev.medium{color:#d29922}
.fix{margin-top:6px;color:var(--muted);font-size:12.5px}
footer{padding:24px 28px;color:var(--muted);font-size:12px;border-top:1px solid var(--border);margin-top:20px}
`
